### ISSUE TITLE
SQL Dump fajl ima grešku

### ISSUE THREAD

**Issue by esinanovic2** [SoftverInzenjeringETFSA/SI2015Tim9#14]
![issue sql](https://cloud.githubusercontent.com/assets/17434546/15300452/0fc61fae-1ba9-11e6-8ebd-55b413b423b4.jpg)
Prilikom ubacivanja podataka u bazu dobio sam grešku koja se vidi u screenshot-u.

**Comment by TheAdnan** [comment]
SQL Dump file i init skripta su namjenski pravljene za MySQL workbench, kao što stoji u Uputstvu za razvojno okruženje, tako da je razlika u sintaksi u drugim sql serverima moguća.
