### ISSUE TITLE
Username i password za korisnika baze nisu navedeni u dokumentaciji

### ISSUE THREAD

**Issue by esinanovic2** [SoftverInzenjeringETFSA/SI2015Tim9#15]
Prilikom pokretanja aplikacije(app.vrtic->App.java) dobijem exception koji kaže da nemam pravo pristupa bazi.
![issue 2](https://cloud.githubusercontent.com/assets/17434546/15300624/d98a0562-1ba9-11e6-8bb9-6fc78fd8f501.jpg)

**Comment by TheAdnan** [comment]
Korisnik i password za bazu je zadan kao po zahtjevu s c2 (može se takođe naći i u konfiguraciji hibernate-a), ali koliko vidim da vaš user nije podešen za localhost, kao što se zahtjevalo.
![screenshot_1](https://cloud.githubusercontent.com/assets/7202517/15304193/36ef6c8a-1bbc-11e6-89df-90935c21e5f4.png)
