### ISSUE TITLE
Polja za ime i prezime primaju sve karaktere, moguć SQL Injection napad

### ISSUE THREAD

**Issue by esinanovic2** [SoftverInzenjeringETFSA/SI2015Tim9#19]
Opis problema:
U polja za ime i prezime forme za izmjenu korisnika se mogu upisati razni karakteri koji nisu slova i neograničen broj karaktera, pa program izbaci izuzetak iz baze i preko ove forme je podložan SQL injection napadu.
Koraci za reprodukciju:
Pokretanje App.java;
login sa akicin1, pass 123
Klik na korisnika, pa na dugme Izmijeni.
Unos neispravnih podataka,
Klik na digme izmijeni
![issue 4](https://cloud.githubusercontent.com/assets/17434546/15302842/54cfb3a6-1bb5-11e6-869e-4335d940f3a2.jpg)

**Comment by dzenana1** [comment]
Nije obradjeno na predmetu i nije se zahtijevalo od nas, također spada u zaštitu sistemabug
