### ISSUE TITLE
Evidencije o uplati (za korisnika tipa Blagajnik)- nedostaje lista mjeseci na formi

### ISSUE THREAD

**Issue by jmuslimovic23** [SoftverInzenjeringETFSA/SI2015Tim9#23]
1.ulogujemo se sa nekim racunom tipa  **"Blagajnik"**
2. u tabu **Evidencija uplate**
3. ako pritisnemo prvo **izracunaj** (gdje jasno obracun jeste 0.00KM) te nakon toga 
button **potvrdi** dobit cemo upozorenje da odaberemo mjesece za koje vrsimo uplatu, ali nigdje ih zapravo ne mozemo odabrati! (button **prikaze mjesece** je neaktivan)...

![evidencija o uplatama nema mjeseci ponudjenih](https://cloud.githubusercontent.com/assets/17432907/15303549/9ecbc406-1bb8-11e6-831a-0dc9a29064a3.jpg)

**Comment by TheAdnan** [comment]
To ovisi kad je napravljen ugovor. Vjerovatno u bazi podaci o napravljenom ugovoru ne obuhvataju 2017 godinu kao što si odabrao, pa je zbog toga spisak prazan.
