### ISSUE TITLE
Problem sa brisanjem aktivnosti

### ISSUE THREAD

**Issue by esinanovic2** [SoftverInzenjeringETFSA/SI2015Tim9#24]
Opis:
Prilikom brisanja aktivnosti aplikacija baci izuzetak.
Koraci za reprodukciju:
Pokretanje aplikacije, login, klik na tab aktivnosti
selektovanje aktivnosti
klik na dugme za brisanje aktivnosti
![issue 7](https://cloud.githubusercontent.com/assets/17434546/15303647/230d220a-1bb9-11e6-9fe0-1d2b86fd717d.jpg)

**Comment by TheAdnan** [comment]
Ispravljeno u commitu: 6edc0f799f93067fee4b824af44f17d642896688
