### ISSUE TITLE
Raspored: preklapanje aktivnosti za iste grupe

### ISSUE THREAD

**Issue by jmuslimovic23** [SoftverInzenjeringETFSA/SI2015Tim9#28]
1. ulogujemo se sa racunom tipa "direkotor"
2. na tabu **Raspored**
3. **kreiraj raspored,** 
4. moguce je dodati novu aktivnost za neku grupu u vremenskom intervali kada ta ista grupa ima vec neku drugu aktivnost... npr sa slike : "_Druga grupa_" ima utorkom Engleski (u periodu 12:00-13:00)
   , a mi smo joj dodali jos Tjelesni odgoj u tom periodu
- takodjer nedostaje button za brisanje aktivnosti iz rasporede i/ili izmjenu rasporeda.
  ![raspored](https://cloud.githubusercontent.com/assets/17432907/15305708/11f8c152-1bc5-11e6-97d8-5f5f11268f84.jpg)

**Comment by TheAdnan** [comment]
Ako stignemo ostale bugove popraviti, onda cemo i ovaj, jer je kompleksniji od ostalih

**Comment by LejlaNukic** [comment]
U SRS-u je za funkcionalnost kreiranje rasporeda kao preduslov navedeno da je korisnik ranije osmislio raspored i u funkcionalne zahtjeve nije stavljeno da sistem vrsi provjeru podataka na nacin da li se aktivnosti preklapaju, da li je raspored smislen i sl.
http://pokit.org/get/?c636a1bac7b9b772a6edd5e15ba8656d.jpg
Takodjer, u funkcionalnostima je navedena samo opcija kreiranja rasporeda i pregleda rasporeda koji je kreiran, a ne mogucnost izmjene tog rasporeda ili brisanja termina/aktivnosti u rasporedu.
U slucaju da je potrebno vrsiti neke modifikacije nad rasporedom, potrebno je kreirati novi raspored koji sadrzi zeljene modifikacije.
