### ISSUE TITLE
Problem nevalidnih polja pri evidentiranju djeteta

### ISSUE THREAD

**Issue by dzanaferatovic** [SoftverInzenjeringETFSA/SI2015Tim9#29]
Komponenta: Interfejs za evidentiranje novog djeteta

Opis problema:
Prilikom evidencije novog djeteta, dozvoljen unos nevalidnih podataka za ime i prezime (dozvoljen unos cifara kao ime i prezime)

Koraci za reprodukciju problema:
1. Prijava na sistem sa korisnickim imenom:akicin1 i passwordom:123
2. Odabir tab "Djeca"
3. Odabir opcije "Evidentiraj dijete"
4. Unos u polja ime, prezime djeteta i ime, prezime staratelja random cifara
5. Odabir opcije "Dodaj"

Dobijeni rezultat: 
![sbsfbs](https://cloud.githubusercontent.com/assets/17457915/15305960/ef125a3e-1bc6-11e6-8f7a-b3d6cb8a8b8a.jpg)

Ocekivani rezultat: Odbijena evidencija djeteta uz odgovarajucu poruku

**Comment by dzanaferatovic** [comment]
Komponenta: Interfejs za evidentiranje novog djeteta

Opis problema:
Prilikom evidencije novog djeteta, dozvoljen unos nevalidnih podataka za datum rodjenja djeteta

Koraci za reprodukciju problema:
1. Prijava na sistem sa korisnickim imenom:akicin1 i passwordom:123
2. Odabir tab "Djeca"
3. Odabir opcije "Evidentiraj dijete"
4. Unos u polje datum rodjenja 29-02-2001 (nevalidan jer 2001 nije prestupna godina)
5. Odabir opcije "Dodaj"

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/17457915/15306080/e927ce50-1bc7-11e6-93f9-a7f982ba53c6.png)

Ocekivani rezultat: Odbijena evidencija djeteta uz odgovarajucu poruku

**Comment by dzanaferatovic** [comment]
Komponenta: Interfejs za evidentiranje novog djeteta

Opis problema:
Prilikom evidencije novog djeteta, dozvoljen unos nevalidnih podataka za datum rodjenja djeteta

Koraci za reprodukciju problema:
1. Prijava na sistem sa korisnickim imenom:akicin1 i passwordom:123
2. Odabir tab "Djeca"
3. Odabir opcije "Evidentiraj dijete"
4. Unos u polje broj telefona 061-111-111aaaaa (nevalidan broj)
5. Odabir opcije "Dodaj"

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/17457915/15306132/5074b0d2-1bc8-11e6-9f63-d73df03a9217.png)

Ocekivani rezultat: Odbijena evidencija djeteta uz odgovarajucu poruku za nevalidnost broja telefona

**Comment by TheAdnan** [comment]
Duplikat #13 issue-a

**Comment by dzanaferatovic** [comment]
Komponenta: Interfejs za evidentiranje novog djeteta

Opis problema:
Prilikom evidencije novog djeteta, dozvoljen unos nevalidnih podataka za datum rodjenja djeteta

Koraci za reprodukciju problema:
1. Prijava na sistem sa korisnickim imenom:akicin1 i passwordom:123
2. Odabir tab "Djeca"
3. Odabir opcije "Evidentiraj dijete"
4. Unos u polje ime "Adi" (validno)
5. Odabir opcije "Dodaj"

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/17457915/15306236/294878e4-1bc9-11e6-9791-e366af997cdd.png)

Ocekivani rezultat: Uspjesna evidencija djeteta
