### ISSUE TITLE
Problem sa unosom novog vaspitaca

### ISSUE THREAD

**Issue by dzanaferatovic** [SoftverInzenjeringETFSA/SI2015Tim9#30]
Komponenta: Interfejs za dodavanje vaspitaca

Opis problema: Nakon unosa validnih podataka na formu, te klikom na dugme "Dodaj vaspitaca" ne desava se nista

Koraci za reprodukciju problema:
1. Prijava na sistem sa korisnickim imenom:akicin1 i passwordom:123
2. Odabir tab "Vaspitaci"
3. Odabir opcije "Dodaj vaspitaca"
4. Unos validnih podataka u sva polja
5. Odabir opcije "Dodaj vaspitaca"

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/17457915/15306384/6b78a314-1bca-11e6-9ed3-479f2af2fbee.png)

Ocekivani rezultat: Dodavanje novog vaspitaca

**Comment by dzanaferatovic** [comment]
- Problem sa brisanjem vaspitaca iz liste dodanih

Komponenta: Interfejs za direktora-Tab vaspitaci

Opis problema: Odabir opcije "Obrisi vaspitaca" ne izaziva nikakvu akciju

Koraci za reprodukciju problema:
1. Prijava na sistem sa korisnickim imenom:akicin1 i passwordom:123
2. Odabir tab "Vaspitaci"
3. Odabir opcije "Obrisi vaspitaca"

**Comment by TheAdnan** [comment]
Vaspitač mora biti odabran da bi se mogao obrisati, inače button i ne treba da ima funkciju.
Vaspitač se pojavljuje nakon dodavanja u tabelu ali tek promjenom taba, što je dupliciran issue.

**Comment by TheAdnan** [comment]
Da li si odabrala vaspitača pa pokušala obrisati, šta se tad desi?
Ako se ni tad ništa ne desi, ovdje napiši pa da ponovo otvorim issue i stavim da je bug.

**Comment by dzanaferatovic** [comment]
Bug se desio iako sam odabrala vaspitaca. Pokusala opet, sad prolazi. Bug+ za Eclipse vjerovatno.
