### ISSUE TITLE
Username nije jedinstven

### ISSUE THREAD

**Issue by jmuslimovic23** [SoftverInzenjeringETFSA/SI2015Tim9#31]
1. logujemo se sa racunom **"direkotora"**
   2.tab **korisnici**
   3.button **dodaj korisnika**
2. moguce je dodati vec postojeceg korisnika,
   -**username nije jedinstven**, tako da je moguce za dodati novog korisnika sa vec postojecim korisnickim imenom i istom ili drugom lozinkom:

![jedinstven username nije](https://cloud.githubusercontent.com/assets/17432907/15306446/e9992430-1bca-11e6-9fa7-4b81ef757a9f.jpg)

**Comment by TheAdnan** [comment]
Popravljeno, commit ID: 2451001d95bae3a0378136822dc4a588a8ce8d8c
