### ISSUE TITLE
Dodavanje grupe sa postojecim rednim brojem validno

### ISSUE THREAD

**Issue by dzanaferatovic** [SoftverInzenjeringETFSA/SI2015Tim9#33]
Komponenta: Interfejs za unos nove grupe

Opis problema:
Unos vec postojeceg rednog broja grupe za novu grupu prolazi, u SRSu naveden uslov validacije:
![image](https://cloud.githubusercontent.com/assets/17457915/15306936/fcbc5998-1bce-11e6-86d3-93ed290d0485.png)

Koraci za reproduciranje problema:
1.Login sa podacima "akicin1" i "123"
2. Odabir taba "Grupe"
3. Odabir opcije "Dodaj grupu"
4. Unos validnih podataka + nevalidan redni broj grupe "1" (Grupa sa tim rednim brojem vec postoji u sistemu)

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/17457915/15306974/3cda5a52-1bcf-11e6-9511-474e4b10a591.png)

Ocekivani rezultat: Odbijanje dodavanja nove grupe sa postojecim rednim brojem

**Comment by TheAdnan** [comment]
#22 issue
