### ISSUE TITLE
Prilikom login-a sa postojećim podacima iz baze, pritiskom na dugme prijava dobijem poruku : "Neispravna šifra!"

### ISSUE THREAD

**Issue by mirelapeskovic** [SoftverInzenjeringETFSA/SI2015Tim9#34]
Komponenta:
Login postojećeg korisnika

Commit ID: 
9fbb26d

Opis problema: Nakon što unesem podatke (ručno) u bazu, ne mogu da se logujem sa postojećim podacima iz baze. Nakon pritiska na dugme prijava dobijem poruku "Neispravna šifra!". 

Koraci za reproduciranje problema:
1. Unijeti podatke o korisniku / korisnicima u bazu (ručno) i refresh šemu. 
2. Pokrenuti aplikaciju. 
3. Log-ovati se kao korisnik iz baze. 
4. Kliknuti dugme "Prijava"

Dobijeni rezultat: 

Messagebox "Neispravna šifra!" (screenshot).
![logingui](https://cloud.githubusercontent.com/assets/11291149/15352667/8e4a8d1e-1ce5-11e6-84ff-6b1d150f2834.jpg)

Podaci u bazi: 
![loginkorisnikbaza](https://cloud.githubusercontent.com/assets/11291149/15352690/abda05f8-1ce5-11e6-9f0b-ef56aee8b4d5.jpg)

Očekivani rezultat: 
"Dugme kojim se potvrđuju uneseni podaci – u slučaju da su podaci validni otvara se glavni prozor aplikacije dok se u slučaju da podaci nisu validni otvara forma sa porukom:“Neispravna šifra!“." - Specifikacija korisničkog interfejsa.

**Comment by TheAdnan** [comment]
Šifra se hešira, a pokretanjem dump.sql filea dobiješ po dva usera (blagajnika i direktora) sa šiframa 123. Detaljnije stoji u komentaru tog sql filea.
