### ISSUE TITLE
Neispravan dump.sql fajl za import baze

### ISSUE THREAD

**Issue by OmarDer** [SoftverInzenjeringETFSA/SI2015Tim9#40]
Datoteka: dump.sql

Opis problema:
Dump.sql datoteka za import podataka u bazu ne radi ispravno i u MySQL Workbenchu. Osim navedenog problema, ova datoteka ima i sintaksnu gresku koju signalizira MySQL Workbench kada datoteku otvorimo.

Koraci za reproduciranje problema:
1. Pokrenuti MySql Workbench.
2. Importovati dump.sql datoteku.

Dobijeni rezultat: http://pokit.org/get/?c125f03838e5e7698bfa7e947801e981.jpg
Ocekivani rezultat: Ispravan import dump.sql datoteke

Napomena: Slican issue je zatvoren #14 , ali ovo je se isto desava i u MySQL Workbenchu.

**Comment by OmarDer** [comment]
Izvinjavam se na pogreski, ovo je poruka koja se dobije prilikom importa.
Dobijeni rezultat :http://pokit.org/get/?aa6401ca978446155464d0d9fe8da018.jpg

**Comment by LejlaNukic** [comment]
Koju verziju workbench-a koristis? :)

**Comment by OmarDer** [comment]
Koristim MYSQL Workbench 6.3, ali imate pogresku u sintaksi u 18. liniji, nemate zatvorenu zagradu u insert upitu: http://pokit.org/get/?4023b929d6188dc34982fdd1fd7fe419.jpg
