### ISSUE TITLE
Nepostojanje informacije o neophodnom formatu prilikom unosa broja telefona staratelja

### ISSUE THREAD

**Issue by OmarDer** [SoftverInzenjeringETFSA/SI2015Tim9#42]
Komponenta: EvidentiranjeDjeteta

Commit ID: 2aa382d
Opis problema: Prikaz poruke upozorenja koja bi sadrzavala neophodni format broja ne postoji, unos broja telefona nije uopste intuitivan, cak se ne poklapa ni sa formatom brojeva koristenih u SRS-u.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju i logovati se sa korisnickim imenom: akicin1 i lozinkom: 123
2. Po otvaranju nove forme izabrati tab "Djeca"
3. Selektirati prvo dijete u tabeli i kliknuti na button "Evidentiraj dijete".
4. Popuniti polja kao na slici, unijeti u polje "Broj telefona staratelja" vrijednost 033/123-456.
5. Kliknuti na button "Dodaj".

Dobijeni rezultat: http://pokit.org/get/?ec43c529d9353fd7743104645106f18c.jpg

Ocekivani rezultat: Omogucena povratna informacija o ispravnom formatu broja, ili login na osnovu trenutno unesenog broja.

**Comment by TheAdnan** [comment]
Izmijeni samo naziv issue-a, jer je issue drugaciji od naslova cini mi se

**Comment by OmarDer** [comment]
Jeste, moja pogreska, popravio sam naziv.
