### ISSUE TITLE
Nemogucnost registriranja vaspitaca uprkos ispravnom unosu

### ISSUE THREAD

**Issue by OmarDer** [SoftverInzenjeringETFSA/SI2015Tim9#44]
Komponenta: DodavanjeVaspitaca

Commit ID: 2aa382d
Opis problema: Prikaz poruke upozorenja nije uredu, jer se unosi korisnik koji ima sve podatke ispravne, pri tome i tekst poruke nije jasan jer glasi: "Neispravan unos imena.".

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Unijeti kao username:"akicin", kao password "123".
3. Odabrati tab "Vaspitaci".
4. Odabarati opciju "Dodaj vaspitaca".
5. Popuniti formu sa podacima kao na slici.
6. Pritisnuti dugme "Dodaj vaspitaca".
Dobijeni rezultat: http://pokit.org/get/?6246c9ffb5e0e1d8dfcf29d8786e1527.jpg

Ocekivani rezultat: Svi uneseni podaci su u ispravnom formati, novi vaspitac bi se trebao moci prijaviti.

**Comment by TheAdnan** [comment]
Jesi li provjerio da li postoji vaspitač koji se tako zove?

**Comment by OmarDer** [comment]
Da provjerio sam i nema podudaranja. Opet se javlja isti problem
