### ISSUE TITLE
Unos veceg broja casova u istom terminu i za istu grupu

### ISSUE THREAD

**Issue by OmarDer** [SoftverInzenjeringETFSA/SI2015Tim9#45]
Komponenta: DodavanjeRasporeda i PrikazProzorDirektor

Commit ID: 2aa382d

Opis problema: Moguce je registrovati vise aktivnosti (npr. engleski, talijanski, njemacki,...) za istu grupu, na isti dan i u isto vrijeme. Generalno, u aplikaciji ne postoji, ili vrlo tesko uociti, neko smisleno pravilo koje bi se postivalo pri registaraciji novih casova. Moguce je takodjer i iste casove dodati u iste termine identicnim grupama, oni se ponovno dodaju i prikazuju iako se dupliciraju.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Unijeti kao username:"akicin", kao password "123".
3. Odabrati tab "Raspored".
4. Odabarati opciju "Kreiraj raspored".
5. Kreirati vise razlicitih casova na isti dan, za istu grupu i u isto vrijeme.

Dobijeni rezultat: http://pokit.org/get/?b4b57666f0672c18e064deb427fc4b37.jpg

Ocekivani rezultat: Nemogucnost unosa ovih casova u istom terminu na isti dan. Clanovi jedne grupe bi trebali da mogu prisustovati samo jednom casu u jednom vremenskom intervalu.

**Comment by TheAdnan** [comment]
Duplicate of #28 issue
