### ISSUE TITLE
Nepostojanje validacije za unos podataka na formi koji se odnose na godinu i datum

### ISSUE THREAD

**Issue by OmarDer** [SoftverInzenjeringETFSA/SI2015Tim9#46]
Komponenta: BlagajnikGlavniProzor

Commit ID: 2aa382d
Opis problema: Moguce je nakon izlistavanja mjeseci ponovno promijeniti polja pored labela "Godina:" i "Datum uplate:", pri tome se moze unijeti bilo koja vrijednost u polja za unos i ta vrijednost se prije izvrsenja operacije ne provjerava. Takodjer, dogovor koji se sklopljen sa strankom prije, prilikom prijave djeteta, a odnosi se na vremensko trajanje ugovora, mogu se prekrsiti, sto za posljedicu ima da se roditelju moze naplatiti clanarina za mjesec koji nije definisan u trajanju ugovora.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Ulogovati se kao blagajnik.
3. Odabarati  ime djeteta i roditelja u listi "Dijete, roditelj: "
4. Odabrati opciju prikazi mjesece, odabrati mjesec, a zatim promijeniti podatke o godini i datumu kao  na slici.
5. Pritisnuti dugme "Potvrdi".

Dobijeni rezultat:http://pokit.org/get/?d5cc5586a507854edb1439cfa96cfcf8.jpg i pri tome, ovako uneseni podaci se spreme u bazu podataka.

Ocekivani rezultat: Pojava informacije o greski.

**Comment by LejlaNukic** [comment]
Za prvi dio si upravu. Sto se tice drugog dijela(vezanog za trajanje ugovora), u intervju-u je receno da se ugovor potpisuje na godinu dana. Sasvim je moguce da se desi prekid ugovora i u tom slucaju je potrebno promijeniti podatke za dijete, konkretno podatak koji se odnosi na trajanje ugovora. Nakon toga se automatski azuriraju odgovarajuce informacije o zaduzenjima i sigurno se nece moci naplatiti mjesec nakon raskida ugovora.

**Comment by LejlaNukic** [comment]
Kolega, upravu ste.
