### ISSUE TITLE
Još uvijek se može dodati grupa sa postojećim rednim brojem

### ISSUE THREAD

**Issue by mirelapeskovic** [SoftverInzenjeringETFSA/SI2015Tim9#47]
Komponenta:
Dodavanje nove grupe.

commit id:
d79b8de

Opis problema: Iako je već prijavljen bug i zatvoren, još uvijek nije ispravljen. Dakle, može se napraviti nova grupa sa postojećim rednim brojem, a u SRS-u piše da redni broj mora biti jedinstven.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Logovati se kao korisnik sa privilegijama direktora
3. Kliknuti tab "Grupe"
4. Kliknuti dugme "Dodaj grupu"
5. Dodati grupu sa postojećim rednim brojem

Dobijeni rezultat : 
Messagebox "Uspješno ste dodali novu grupu!" (screenshot).

![dodavanjegrupe](https://cloud.githubusercontent.com/assets/11291149/15421150/f6d3654e-1e71-11e6-9b9d-29f96aa9b016.jpg)

Očekivani rezultat:
Poruka o neuspješnom dodavanju grupe zbog postojećeg rednog broja.

**Comment by TheAdnan** [comment]
fixed with commit: 0fda8d0981a7091cb2a9f44d904b20c6cd157662
