### ISSUE TITLE
Nemogućnost brisanja grupe koja je već postojala u bazi (ranije dodana, u nekoj sesiji)

### ISSUE THREAD

**Issue by mirelapeskovic** [SoftverInzenjeringETFSA/SI2015Tim9#48]
Komponenta:
Brisanje grupe

Commit id:
d79b8de  

Opis problema: Nakon što se pokrene aplikacija i uspješno učitaju ranije dodane grupe iz baze, nemoguće je obrisati te iste grupe. Nema problema sa brisanjem grupa koje su dodane u toj sesiji. Nekad obriše, ali češće ne. Uglavnom, prvu odabranu neće da obriše.

Koraci za reproduciranje problema:
1.Pokrenuti aplikaciju
2.Dodati grupu/grupe
3.Ugasiti aplikaciju
4.Provjeriti da li je uspješno sačuvana nova grupa/grupe u bazi (meni jeste)
5. Opet pokrenuti aplikaciju
6. Probati obrisati grupu koja je ranije dodana (odabir grupe, dugme obrisi)

Dobijeni rezultat: (screenshot)
Nakon što se pritisne dugme obriši ne desi se ništa.
![brisanje1](https://cloud.githubusercontent.com/assets/11291149/15421816/a7c9fbf8-1e75-11e6-92ed-fe09b77c3812.jpg)
![brisanje2](https://cloud.githubusercontent.com/assets/11291149/15421826/afc5fa00-1e75-11e6-9c1b-1fa34d67806b.jpg)

Očekivani rezultat: 
Brisanje odabrane grupe i poruka o uspješnom brisanju

**Comment by TheAdnan** [comment]
commit ID: 0fda8d0981a7091cb2a9f44d904b20c6cd157662
