### ISSUE TITLE
Pogrešan redni broj pri dodavanju grupa

### ISSUE THREAD

**Issue by mirelapeskovic** [SoftverInzenjeringETFSA/SI2015Tim9#49]
Komponenta:
Dodavanje nove grupe

Commit ID:
0fda8d0

Opis problema: Nakon što dodam grupu, uneseni redni broj i redni broj koji se prikazuje nisu isti, ili nisu dosljedni (po redu)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Logovati se kao korisnik sa privilegijama direktora
3. Tab Grupe
4. Dodati grupu 

Dobijeni rezultat:
(screenshot)
![dodavanjegrupepogresanrednibroj](https://cloud.githubusercontent.com/assets/11291149/15422116/1401405a-1e77-11e6-9a38-5e6bbc2a6d24.jpg)

![rezultatpogresanrednibroj](https://cloud.githubusercontent.com/assets/11291149/15422123/1d8bafd4-1e77-11e6-9f0d-427f4b754f10.jpg)

Očekivani rezultat:
Konsistentni redni brojevi

**Comment by TheAdnan** [comment]
Nije navedeno da će grupe biti sortirane, niti da moraju biti jedna za drugom po rednim. Zbog toga se i unose kroz formu redni brojevi :)
