### ISSUE TITLE
Moguće je izvršiti uplatu i birati datum uplate koji je veći od trenutnog

### ISSUE THREAD

**Issue by mirelapeskovic** [SoftverInzenjeringETFSA/SI2015Tim9#50]
Komponenta:
Evidencija uplate

Commit ID:
0fda8d0

Opis problema: 
Moguće je izvršiti uplatu na datum koji je poslije trenutnog.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju
2. Logovati se kao korisnik sa privilegijama blagajnika
3. Izvršiti uplatu na datum koji je poslije trenutnog

Dobijeni rezulat: 
Messagebox "Uplata školarine je uspješno evidentirana!" (screenshot).
![datumuplate](https://cloud.githubusercontent.com/assets/11291149/15422836/ba8a4086-1e7a-11e6-8450-f119f53fed98.jpg)

Očekivani rezultat:
Poruka da je nemoguće nešto uplatiti na datum koji je poslije trenutnog.

**Comment by LejlaNukic** [comment]
Duplikat od #46.
