### ISSUE TITLE
par prijedloga

### ISSUE THREAD

**Issue by jmuslimovic23** [SoftverInzenjeringETFSA/SI2015Tim9#52]
imam nekoliko prijedloga koji se odnose na par sitnica:

ulogujemo se sa nalogom "direkora" (username: akicin1 ,password: 123)
1. **tab Raspored** 
   nedostaje button za brisanje aktivnosti u rasporedu , jer moze doci do greske prilkom unosa aktivnosti, ili cak određenih promjena  u rasporedu i nastat ce problem
   ![p1 nedostaje button za brisanje](https://cloud.githubusercontent.com/assets/17432907/15425966/d88cb616-1e8b-11e6-85a4-f18cab322a3b.jpg)
2. **Resize prozora** dio sadrzaja postaje **nevidljiv i nepristupacan**, bilo bi pozeljno ako je moguce da ima **vertikalni klizac**:
   ![nedostaje vertikalni klizac na prozuru kod resize](https://cloud.githubusercontent.com/assets/17432907/15426003/11a9ecde-1e8c-11e6-8a85-3e9b442fe421.jpg)
3. zbog konzistentnosti cijele aplikacije , pozeljno bi bilo da **godina bude bez decimalnog zareza**, 
   (godina sa decimalnim zarezom kod blagajnika ispravljena - kod direktora nije)
   ![godina sa decimalnim zarezom kod blagajnika ispravljena - kod direktora nije](https://cloud.githubusercontent.com/assets/17432907/15426015/27f876fe-1e8c-11e6-92cb-142f9a905808.jpg)

**Comment by LejlaNukic** [comment]
Kolega, treci prijedlog cemo usvojiti. :)
Kada je rijec o prva dva prijedloga, funkcionalni zahtjevi su tako definisani i usvojeni da nije predvidjena modifikacija rasporeda na taj nacin. Naravno, postoji mogucnost da se ovaj sistem dodatno prosiri, kao i da se neke funkcionalnosti drugacije realizuju, ali to trenutno izlazi van opsega sistema koji je opisan u ostalim dokumentima.
