### ISSUE TITLE
Unos godine je prikazan sa decimalnim zarezom

### ISSUE THREAD

**Issue by Filadendron** [SoftverInzenjeringETFSA/SI2015Tim9#54]
Komponenta: Uplate koje kasne
Commit ID: 2d14cfc
Opis problema: Kada se klikne na tab uplate koje kasne i krene kucati godina , na godinu doda decimalni zarez.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Unijeti kao username:"akicin", kao password "123".
3. Odabrati tab "Uplate koje kasne".
4. Popuniti formu sa podacima kao na slici.
Dobijeni rezultat: http://pokit.org/get/?5844d9a3c5b3dc4185de6839ffaaf6a1.jpg

Ocekivani rezultat: Ocekivano je da za ne validnu godinu 2,016 ispise poruku o gresci.

**Comment by TheAdnan** [comment]
#52
