### ISSUE TITLE
Forma za unos aktivnosti i dalje funkcionalna nakon logouta

### ISSUE THREAD

**Issue by Filadendron** [SoftverInzenjeringETFSA/SI2015Tim9#55]
Komponenta: Dodavanje aktivnosti
Commit ID: 2d14cfc
Opis problema: Ako se na tabu "Aktivnosti" klikne na dugme "Dodaj aktivnost" i pri tome izloguje forma za dodavanje Aktivnosti ce ostati aktivna i funkcionalna pri cemu se nova aktivnost uspjesno doda u bazu .

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Unijeti kao username:"akicin", kao password "123".
3. Odabrati tab "Aktivnosti".
4. Odabarati opciju "Dodaj aktivnost".
5. Pritisnuti dugme "Logout".
6. Popuniti formu sa podacima kao na slici.
Dobijeni rezultat: http://pokit.org/get/?044f79eb05c43926476214b7bcd7d52d.jpg
                           http://pokit.org/get/?50803d1a68d36adc9da2ef4151ec35ed.jpg

Ocekivani rezultat: Ocekivano je da forma za unos novosti nestane kao i glavna forma pri logoutu.

**Comment by TheAdnan** [comment]
#51
