### ISSUE TITLE
Problem kod izmjene podataka djeteta->aktivnosti

### ISSUE THREAD

**Issue by dzanaferatovic** [SoftverInzenjeringETFSA/SI2015Tim9#60]
Komponenta: Interfejs za izmjenu podataka postojeceg djeteta

commit id: https://github.com/SoftverInzenjeringETFSA/SI2015Tim9/commit/1851324871ee14ce3c49c0c1ccee78f0799c3d31

Opis problema:
Forma za izmjenu podataka za postojece dijete u dijelu sa aktivnostima koje dijete moze pohadjati prikazuje aktivnosti koje dijete vec pohadja. Odabirom aktivnosti koju dijete vec pohadja u listu moguce opet dodati istu. Spsasavanje takvih izmjena ne prijavljuje gresku niti prihvata izmjene.

Koraci za reproduciranje problema:
1. Login sa podacima akicin1, 123
2. Odabir taba "Djeca"
3. Odabir djeteta "Dzana Feratovic" (dodanim sa validnim podacima)
4. Odabir opcije "Izmijeni podatke"
5. Dodavanje vec postojece aktivnosti vezane za dijete ("Engleski") moguce dodati opet
6. Spasavanje izmjena

Dobijeni rezultat:
![image](https://cloud.githubusercontent.com/assets/17457915/15436011/f5522068-1ebf-11e6-8f62-8450b000dc1f.png)

Ne prijavljuje se nikakva poruka o gresci, niti uspjesnom spasavanju izmjena.

Ocekivani rezultat:
Nemogucnost dodavanja aktivnosti za dijete koje vec pohadja istu, ili barem poruka o nemogucnosti spasavanja takvih (nevalidnih) izmjena.

Slican problem sa brisanjem aktivnosti za dijete. Odabirom aktivnosti "Njemacki" i buttona "<<", u listi za odabir se pojavljuju dvije aktivnosti "Njemacki".
![image](https://cloud.githubusercontent.com/assets/17457915/15436107/7945c104-1ec0-11e6-8911-3c0e4fc409f0.png)

**Comment by LejlaNukic** [comment]
Kolegice, da li biste nam, molim Vas, mogli napraviti screenshot tabele aktivnosti iz baze?
Unaprijed hvala.

**Comment by dzanaferatovic** [comment]
![image](https://cloud.githubusercontent.com/assets/17457915/15441034/dfbcc2e4-1ed8-11e6-83ae-3fd73ce6d3d2.png)
